spring.jpa.properties.hibernate.hbm2ddl.jdbc_metadata_extraction_strategy=individually

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${ARKIVE_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=never

arkive.bootstrap.sysadmin.enabled=${ARKIVE_BOOTSTRAP_SYSADMIN_ENABLED:false}
arkive.bootstrap.sysadmin.name=${ARKIVE_BOOTSTRAP_SYSADMIN_NAME:}
arkive.bootstrap.sysadmin.login=${ARKIVE_BOOTSTRAP_SYSADMIN_LOGIN:}
arkive.bootstrap.sysadmin.password=${ARKIVE_BOOTSTRAP_SYSADMIN_PASSWORD:}

