-- Canonical ArkIve pre-Sprint-3 schema for clean databases.
-- Derived from docs/database/Arkive_modelo_oracle_v6.sql (Oracle) and converted for
-- Azure SQL Database / Microsoft SQL Server, with the environment preparation block
-- intentionally excluded.

CREATE TABLE TB_ARKIVE_ESPECIE (
    ID_ESPECIE BIGINT IDENTITY(1,1) NOT NULL,
    NM_ESPECIE VARCHAR(50) NOT NULL,
    ST_ATIVO CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT PK_ARKIVE_ESPECIE PRIMARY KEY (ID_ESPECIE),
    CONSTRAINT UQ_ARKIVE_ESPECIE_NOME UNIQUE (NM_ESPECIE),
    CONSTRAINT CK_ARKIVE_ESPECIE_ATIVO CHECK (ST_ATIVO IN ('S', 'N'))
);
-- TB_ARKIVE_ESPECIE: Catalogo de especies animais.
-- TB_ARKIVE_ESPECIE.ID_ESPECIE: Identificador unico da especie.
-- TB_ARKIVE_ESPECIE.NM_ESPECIE: Nome da especie, como Cao, Gato ou Ave.
-- TB_ARKIVE_ESPECIE.ST_ATIVO: Indica exclusao logica da especie: S = ativo, N = inativo.

CREATE TABLE TB_ARKIVE_RACA (
    ID_RACA BIGINT IDENTITY(1,1) NOT NULL,
    NM_RACA VARCHAR(50) NOT NULL,
    ID_ESPECIE BIGINT NOT NULL,
    TP_PORTE VARCHAR(20) NULL,
    ST_ATIVO CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT PK_ARKIVE_RACA PRIMARY KEY (ID_RACA),
    CONSTRAINT UQ_ARKIVE_RACA_ESPECIE_NOME UNIQUE (ID_ESPECIE, NM_RACA),
    CONSTRAINT CK_ARKIVE_RACA_PORTE CHECK (TP_PORTE IS NULL OR TP_PORTE IN ('PEQUENO', 'MEDIO', 'GRANDE')),
    CONSTRAINT FK_RACA_ESPECIE FOREIGN KEY (ID_ESPECIE)
        REFERENCES TB_ARKIVE_ESPECIE (ID_ESPECIE),
    CONSTRAINT CK_ARKIVE_RACA_ATIVO CHECK (ST_ATIVO IN ('S', 'N'))
);
-- TB_ARKIVE_RACA: Catalogo de racas vinculadas a uma especie.
-- TB_ARKIVE_RACA.ID_RACA: Identificador unico da raca.
-- TB_ARKIVE_RACA.NM_RACA: Nome da raca.
-- TB_ARKIVE_RACA.ID_ESPECIE: Especie da raca.
-- TB_ARKIVE_RACA.TP_PORTE: Porte predominante da raca.
-- TB_ARKIVE_RACA.ST_ATIVO: Indica exclusao logica da raca: S = ativo, N = inativo.

CREATE TABLE TB_ARKIVE_RESPONSAVEL (
    ID_RESPONSAVEL BIGINT IDENTITY(1,1) NOT NULL,
    NM_RESPONSAVEL VARCHAR(50) NOT NULL,
    DC_CPF_RG VARCHAR(20) NOT NULL,
    DS_EMAIL VARCHAR(200) NULL,
    NR_CONTATO VARCHAR(20) NULL,
    TP_RESPONSAVEL VARCHAR(30) NOT NULL,
    DT_CADASTRO DATE NOT NULL DEFAULT GETDATE(),
    ST_NOTIFICACAO CHAR(1) NOT NULL DEFAULT 'S',
    ST_ATIVO CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT PK_ARKIVE_RESPONSAVEL PRIMARY KEY (ID_RESPONSAVEL),
    CONSTRAINT UQ_ARKIVE_RESPONSAVEL_DOC UNIQUE (DC_CPF_RG),
    CONSTRAINT CK_ARKIVE_RESP_TIPO CHECK (TP_RESPONSAVEL IN ('TUTOR', 'FUNCIONARIO_CLINICA', 'FUNCIONARIO_ZOO', 'ONG', 'INSTITUICAO', 'OUTRO')),
    CONSTRAINT CK_ARKIVE_RESP_NOTIF CHECK (ST_NOTIFICACAO IN ('S', 'N')),
    CONSTRAINT CK_ARKIVE_RESP_ATIVO CHECK (ST_ATIVO IN ('S', 'N'))
);
-- TB_ARKIVE_RESPONSAVEL: Pessoa, instituicao ou contato que pode se relacionar com um animal em contexto B2C ou B2B.
-- TB_ARKIVE_RESPONSAVEL.ID_RESPONSAVEL: Identificador unico do responsavel.
-- TB_ARKIVE_RESPONSAVEL.NM_RESPONSAVEL: Nome do responsavel, funcionario, instituicao, ONG ou contato.
-- TB_ARKIVE_RESPONSAVEL.DC_CPF_RG: CPF, CNPJ ou outro identificador, quando aplicavel.
-- TB_ARKIVE_RESPONSAVEL.DS_EMAIL: E-mail de contato do responsavel.
-- TB_ARKIVE_RESPONSAVEL.NR_CONTATO: Telefone de contato do responsavel.
-- TB_ARKIVE_RESPONSAVEL.TP_RESPONSAVEL: Tipo do responsavel: TUTOR, FUNCIONARIO_CLINICA, FUNCIONARIO_ZOO, ONG, INSTITUICAO ou OUTRO.
-- TB_ARKIVE_RESPONSAVEL.DT_CADASTRO: Data de cadastro do responsavel.
-- TB_ARKIVE_RESPONSAVEL.ST_NOTIFICACAO: Indica se aceita notificacoes: S ou N.
-- TB_ARKIVE_RESPONSAVEL.ST_ATIVO: Indica exclusao logica: S = ativo, N = inativo.

CREATE TABLE TB_ARKIVE_CLINICA (
    ID_CLINICA BIGINT IDENTITY(1,1) NOT NULL,
    NM_CLINICA VARCHAR(150) NOT NULL,
    DC_CNPJ VARCHAR(14) NOT NULL,
    DS_ENDERECO VARCHAR(255) NULL,
    NR_CONTATO VARCHAR(20) NULL,
    DS_EMAIL VARCHAR(200) NULL,
    ST_ATIVO CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT PK_ARKIVE_CLINICA PRIMARY KEY (ID_CLINICA),
    CONSTRAINT UQ_ARKIVE_CLINICA_CNPJ UNIQUE (DC_CNPJ),
    CONSTRAINT CK_ARKIVE_CLINICA_ATIVO CHECK (ST_ATIVO IN ('S', 'N'))
);
-- TB_ARKIVE_CLINICA: Clinica ou hospital veterinario parceiro.
-- TB_ARKIVE_CLINICA.ID_CLINICA: Identificador unico da clinica.
-- TB_ARKIVE_CLINICA.NM_CLINICA: Nome da clinica.
-- TB_ARKIVE_CLINICA.DC_CNPJ: CNPJ da clinica.
-- TB_ARKIVE_CLINICA.DS_ENDERECO: Endereco da clinica.
-- TB_ARKIVE_CLINICA.NR_CONTATO: Telefone de contato da clinica.
-- TB_ARKIVE_CLINICA.DS_EMAIL: E-mail de contato da clinica.
-- TB_ARKIVE_CLINICA.ST_ATIVO: Indica exclusao logica: S = ativo, N = inativo.

CREATE TABLE TB_ARKIVE_RESPONSAVEL_CLINICA (
    ID_RESPONSAVEL BIGINT NOT NULL,
    ID_CLINICA BIGINT NOT NULL,
    DT_VINCULO DATE NOT NULL DEFAULT GETDATE(),

    CONSTRAINT PK_ARKIVE_RESP_CLINICA PRIMARY KEY (ID_RESPONSAVEL, ID_CLINICA),
    CONSTRAINT FK_RESPCLDS_RESP FOREIGN KEY (ID_RESPONSAVEL)
        REFERENCES TB_ARKIVE_RESPONSAVEL (ID_RESPONSAVEL),
    CONSTRAINT FK_RESPCLDS_CLINICA FOREIGN KEY (ID_CLINICA)
        REFERENCES TB_ARKIVE_CLINICA (ID_CLINICA)
);
-- TB_ARKIVE_RESPONSAVEL_CLINICA: Relacionamento N:N entre responsaveis e clinicas onde existe vinculo operacional, clinico ou de atendimento.
-- TB_ARKIVE_RESPONSAVEL_CLINICA.ID_RESPONSAVEL: Responsavel vinculado a clinica.
-- TB_ARKIVE_RESPONSAVEL_CLINICA.ID_CLINICA: Clinica vinculada ao responsavel.
-- TB_ARKIVE_RESPONSAVEL_CLINICA.DT_VINCULO: Data de criacao do vinculo.

CREATE TABLE TB_ARKIVE_VETERINARIO (
    ID_VETERINARIO BIGINT IDENTITY(1,1) NOT NULL,
    NM_VETERINARIO VARCHAR(50) NOT NULL,
    DC_CRMV VARCHAR(10) NOT NULL,
    DS_ESPECIALIDADE VARCHAR(50) NULL,
    DS_EMAIL VARCHAR(200) NULL,
    ID_CLINICA BIGINT NULL,
    ST_ATIVO CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT PK_ARKIVE_VETERINARIO PRIMARY KEY (ID_VETERINARIO),
    CONSTRAINT UQ_ARKIVE_CRMV UNIQUE (DC_CRMV),
    CONSTRAINT CK_ARKIVE_VET_ATIVO CHECK (ST_ATIVO IN ('S', 'N')),
    CONSTRAINT FK_VET_CLINICA FOREIGN KEY (ID_CLINICA)
        REFERENCES TB_ARKIVE_CLINICA (ID_CLINICA)
);
-- TB_ARKIVE_VETERINARIO: Profissional veterinario, vinculado ou nao a uma clinica.
-- TB_ARKIVE_VETERINARIO.ID_VETERINARIO: Identificador unico do veterinario.
-- TB_ARKIVE_VETERINARIO.NM_VETERINARIO: Nome completo do veterinario, sem titulo profissional como Dr. ou Dra.
-- TB_ARKIVE_VETERINARIO.DC_CRMV: Registro profissional do veterinario.
-- TB_ARKIVE_VETERINARIO.DS_ESPECIALIDADE: Especialidade do veterinario.
-- TB_ARKIVE_VETERINARIO.DS_EMAIL: E-mail do veterinario.
-- TB_ARKIVE_VETERINARIO.ID_CLINICA: Clinica fixa do veterinario; nulo para autonomo.
-- TB_ARKIVE_VETERINARIO.ST_ATIVO: Indica exclusao logica: S = ativo, N = inativo.

CREATE TABLE TB_ARKIVE_USUARIO (
    ID_USUARIO BIGINT IDENTITY(1,1) NOT NULL,
    TP_USUARIO VARCHAR(20) NOT NULL,
    ID_RESPONSAVEL BIGINT NULL,
    ID_VETERINARIO BIGINT NULL,
    DS_LOGIN VARCHAR(200) NOT NULL,
    DS_SENHA_HASH VARCHAR(255) NOT NULL,
    DT_CADASTRO DATETIME2 NOT NULL DEFAULT GETDATE(),
    ST_ATIVO CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT PK_ARKIVE_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UQ_ARKIVE_USUARIO_LOGIN UNIQUE (DS_LOGIN),
    CONSTRAINT CK_ARKIVE_USUARIO_TIPO CHECK (TP_USUARIO IN ('RESPONSAVEL', 'VETERINARIO')),
    CONSTRAINT CK_ARKIVE_USUARIO_ATIVO CHECK (ST_ATIVO IN ('S', 'N')),
    CONSTRAINT CK_ARKIVE_USUARIO_REF CHECK (
        (TP_USUARIO = 'RESPONSAVEL' AND ID_RESPONSAVEL IS NOT NULL AND ID_VETERINARIO IS NULL)
        OR
        (TP_USUARIO = 'VETERINARIO' AND ID_VETERINARIO IS NOT NULL AND ID_RESPONSAVEL IS NULL)
    ),
    CONSTRAINT FK_USUARIO_RESP FOREIGN KEY (ID_RESPONSAVEL)
        REFERENCES TB_ARKIVE_RESPONSAVEL (ID_RESPONSAVEL),
    CONSTRAINT FK_USUARIO_VET FOREIGN KEY (ID_VETERINARIO)
        REFERENCES TB_ARKIVE_VETERINARIO (ID_VETERINARIO)
);

-- ID_RESPONSAVEL and ID_VETERINARIO are nullable optional 1:1 links (most rows have one
-- of them NULL). Unlike Oracle, a plain SQL Server UNIQUE constraint/index tolerates only
-- ONE NULL per table, which would break on the second such row. Filtered unique indexes
-- (unique only where the value is present) reproduce Oracle's "NULLs are not compared" behavior.
CREATE UNIQUE INDEX UQ_ARKIVE_USUARIO_RESP ON TB_ARKIVE_USUARIO (ID_RESPONSAVEL)
    WHERE ID_RESPONSAVEL IS NOT NULL;
CREATE UNIQUE INDEX UQ_ARKIVE_USUARIO_VET ON TB_ARKIVE_USUARIO (ID_VETERINARIO)
    WHERE ID_VETERINARIO IS NOT NULL;

-- TB_ARKIVE_USUARIO: Credenciais de acesso de responsaveis e veterinarios.
-- TB_ARKIVE_USUARIO.ID_USUARIO: Identificador unico do usuario.
-- TB_ARKIVE_USUARIO.TP_USUARIO: Tipo de usuario: RESPONSAVEL ou VETERINARIO.
-- TB_ARKIVE_USUARIO.ID_RESPONSAVEL: Responsavel associado ao usuario, quando aplicavel.
-- TB_ARKIVE_USUARIO.ID_VETERINARIO: Veterinario associado ao usuario, quando aplicavel.
-- TB_ARKIVE_USUARIO.DS_LOGIN: Login do usuario.
-- TB_ARKIVE_USUARIO.DS_SENHA_HASH: Hash da senha do usuario.
-- TB_ARKIVE_USUARIO.DT_CADASTRO: Data de criacao da conta.
-- TB_ARKIVE_USUARIO.ST_ATIVO: Indica exclusao logica: S = ativo, N = inativo.

CREATE TABLE TB_ARKIVE_ANIMAL (
    ID_ANIMAL BIGINT IDENTITY(1,1) NOT NULL,
    NM_ANIMAL VARCHAR(50) NOT NULL,
    ID_ESPECIE BIGINT NOT NULL,
    ID_RACA BIGINT NULL,
    DS_SEXO CHAR(1) NULL,
    DS_CASTRADO CHAR(1) NOT NULL DEFAULT 'N',
    ID_CLINICA BIGINT NULL,
    ST_ATIVO CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT PK_ARKIVE_ANIMAL PRIMARY KEY (ID_ANIMAL),
    CONSTRAINT CK_ARKIVE_ANIMAL_ATIVO CHECK (ST_ATIVO IN ('S', 'N')),
    CONSTRAINT CK_ARKIVE_ANIMAL_SEXO CHECK (DS_SEXO IN ('M', 'F')),
    CONSTRAINT CK_ARKIVE_ANIMAL_CASTRADO CHECK (DS_CASTRADO IN ('S', 'N')),
    CONSTRAINT FK_ANIMAL_ESPECIE FOREIGN KEY (ID_ESPECIE)
        REFERENCES TB_ARKIVE_ESPECIE (ID_ESPECIE),
    CONSTRAINT FK_ANIMAL_RACA FOREIGN KEY (ID_RACA)
        REFERENCES TB_ARKIVE_RACA (ID_RACA),
    CONSTRAINT FK_ANIMAL_CLINICA_CAD FOREIGN KEY (ID_CLINICA)
        REFERENCES TB_ARKIVE_CLINICA (ID_CLINICA)
);
-- TB_ARKIVE_ANIMAL: Pet cadastrado no sistema. Nao exige responsavel individual direto, permitindo cadastro por clinica, hospital, ONG, abrigo ou zoologico.
-- TB_ARKIVE_ANIMAL.ID_ANIMAL: Identificador unico do animal.
-- TB_ARKIVE_ANIMAL.NM_ANIMAL: Nome do animal.
-- TB_ARKIVE_ANIMAL.ID_ESPECIE: Especie do animal.
-- TB_ARKIVE_ANIMAL.ID_RACA: Raca do animal, quando conhecida.
-- TB_ARKIVE_ANIMAL.DS_SEXO: Sexo do animal: M ou F.
-- TB_ARKIVE_ANIMAL.DS_CASTRADO: Indica se o animal e castrado: S ou N.
-- TB_ARKIVE_ANIMAL.ID_CLINICA: Clinica ou instituicao que cadastrou o animal, quando aplicavel.
-- TB_ARKIVE_ANIMAL.ST_ATIVO: Indica exclusao logica: S = ativo, N = inativo.

CREATE TABLE TB_ARKIVE_RESPONSAVEL_ANIMAL (
    ID_ANIMAL BIGINT NOT NULL,
    ID_RESPONSAVEL BIGINT NOT NULL,
    TP_VINCULO VARCHAR(40) NOT NULL,
    DT_INICIO DATE NOT NULL DEFAULT GETDATE(),
    DT_FIM DATE NULL,
    ST_PRINCIPAL CHAR(1) NOT NULL DEFAULT 'N',
    ST_ATIVO CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT PK_ARKIVE_ANIMAL_RESP PRIMARY KEY (ID_ANIMAL, ID_RESPONSAVEL, DT_INICIO),
    CONSTRAINT CK_ARKIVE_ANIRESP_VINCULO CHECK (TP_VINCULO IN ('TUTOR_LEGAL', 'CUIDADOR', 'RESPONSAVEL_CLINICO', 'RESPONSAVEL_OPERACIONAL', 'CONTATO_EMERGENCIA')),
    CONSTRAINT CK_ARKIVE_ANIRESP_PRINC CHECK (ST_PRINCIPAL IN ('S', 'N')),
    CONSTRAINT CK_ARKIVE_ANIRESP_ATIVO CHECK (ST_ATIVO IN ('S', 'N')),
    CONSTRAINT CK_ARKIVE_ANIRESP_DATAS CHECK (DT_FIM IS NULL OR DT_FIM >= DT_INICIO),
    CONSTRAINT FK_ANIRESP_ANIMAL FOREIGN KEY (ID_ANIMAL)
        REFERENCES TB_ARKIVE_ANIMAL (ID_ANIMAL),
    CONSTRAINT FK_ANIRESP_RESP FOREIGN KEY (ID_RESPONSAVEL)
        REFERENCES TB_ARKIVE_RESPONSAVEL (ID_RESPONSAVEL)
);
-- TB_ARKIVE_RESPONSAVEL_ANIMAL: Relacionamento historico entre animais e responsaveis, permitindo multiplos responsaveis, principal e substituicoes ao longo do tempo.
-- TB_ARKIVE_RESPONSAVEL_ANIMAL.ID_ANIMAL: Animal vinculado ao responsavel.
-- TB_ARKIVE_RESPONSAVEL_ANIMAL.ID_RESPONSAVEL: Responsavel vinculado ao animal.
-- TB_ARKIVE_RESPONSAVEL_ANIMAL.TP_VINCULO: Tipo de vinculo entre animal e responsavel.
-- TB_ARKIVE_RESPONSAVEL_ANIMAL.DT_INICIO: Data de inicio do vinculo.
-- TB_ARKIVE_RESPONSAVEL_ANIMAL.DT_FIM: Data de fim do vinculo, quando encerrado.
-- TB_ARKIVE_RESPONSAVEL_ANIMAL.ST_PRINCIPAL: Indica se e o responsavel principal: S ou N.
-- TB_ARKIVE_RESPONSAVEL_ANIMAL.ST_ATIVO: Indica se o vinculo esta ativo: S ou N.

CREATE TABLE TB_ARKIVE_CATEGORIA_DOENCA (
    ID_CATEGORIA BIGINT IDENTITY(1,1) NOT NULL,
    NM_CATEGORIA VARCHAR(100) NOT NULL,
    ST_ATIVO CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT PK_ARKIVE_CATEGORIA_DOENCA PRIMARY KEY (ID_CATEGORIA),
    CONSTRAINT UQ_ARKIVE_CATEGORIA_NOME UNIQUE (NM_CATEGORIA),
    CONSTRAINT CK_ARKIVE_CATDOENCA_ATIVO CHECK (ST_ATIVO IN ('S', 'N'))
);
-- TB_ARKIVE_CATEGORIA_DOENCA: Dominio de categorias clinicas de doencas.
-- TB_ARKIVE_CATEGORIA_DOENCA.ID_CATEGORIA: Identificador unico da categoria.
-- TB_ARKIVE_CATEGORIA_DOENCA.NM_CATEGORIA: Nome da categoria clinica.
-- TB_ARKIVE_CATEGORIA_DOENCA.ST_ATIVO: Indica exclusao logica da categoria de doenca: S = ativo, N = inativo.

CREATE TABLE TB_ARKIVE_DOENCA (
    ID_DOENCA BIGINT IDENTITY(1,1) NOT NULL,
    NM_DOENCA VARCHAR(100) NOT NULL,
    ID_CATEGORIA BIGINT NULL,
    DS_DOENCA VARCHAR(MAX) NULL,
    CD_CID_VET VARCHAR(20) NULL,
    DS_SINTOMAS VARCHAR(MAX) NULL,
    ST_ATIVO CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT PK_ARKIVE_DOENCA PRIMARY KEY (ID_DOENCA),
    CONSTRAINT UQ_ARKIVE_DOENCA_NOME UNIQUE (NM_DOENCA),
    CONSTRAINT FK_DOENCA_CATEGORIA FOREIGN KEY (ID_CATEGORIA)
        REFERENCES TB_ARKIVE_CATEGORIA_DOENCA (ID_CATEGORIA),
    CONSTRAINT CK_ARKIVE_DOENCA_ATIVO CHECK (ST_ATIVO IN ('S', 'N'))
);
-- TB_ARKIVE_DOENCA: Catalogo de doencas e condicoes clinicas.
-- TB_ARKIVE_DOENCA.ID_DOENCA: Identificador unico da doenca.
-- TB_ARKIVE_DOENCA.NM_DOENCA: Nome da doenca ou condicao clinica.
-- TB_ARKIVE_DOENCA.ID_CATEGORIA: Categoria clinica da doenca, referenciada na tabela de dominio.
-- TB_ARKIVE_DOENCA.DS_DOENCA: Descricao resumida da doenca.
-- TB_ARKIVE_DOENCA.CD_CID_VET: Codigo veterinario, quando aplicavel.
-- TB_ARKIVE_DOENCA.DS_SINTOMAS: Palavras-chave usadas no motor de regras.
-- TB_ARKIVE_DOENCA.ST_ATIVO: Indica exclusao logica da doenca: S = ativo, N = inativo.

CREATE TABLE TB_ARKIVE_PREDISPOSICAO (
    ID_PREDISPOSICAO BIGINT IDENTITY(1,1) NOT NULL,
    ID_ESPECIE BIGINT NOT NULL,
    ID_RACA BIGINT NULL,
    ID_DOENCA BIGINT NOT NULL,

    CONSTRAINT PK_ARKIVE_PREDISPOSICAO PRIMARY KEY (ID_PREDISPOSICAO),
    CONSTRAINT FK_PRED_ESPECIE FOREIGN KEY (ID_ESPECIE)
        REFERENCES TB_ARKIVE_ESPECIE (ID_ESPECIE),
    CONSTRAINT FK_PRED_RACA FOREIGN KEY (ID_RACA)
        REFERENCES TB_ARKIVE_RACA (ID_RACA),
    CONSTRAINT FK_PRED_DOENCA FOREIGN KEY (ID_DOENCA)
        REFERENCES TB_ARKIVE_DOENCA (ID_DOENCA)
);

-- SQL Server does not support function-based indexes like Oracle's NVL(ID_RACA, 0).
-- A persisted computed column reproduces the same "treat NULL race as 0" uniqueness rule.
ALTER TABLE TB_ARKIVE_PREDISPOSICAO ADD ID_RACA_COALESCE AS (ISNULL(ID_RACA, 0)) PERSISTED;

CREATE UNIQUE INDEX UX_ARKIVE_PREDISPOSICAO
    ON TB_ARKIVE_PREDISPOSICAO (ID_ESPECIE, ID_RACA_COALESCE, ID_DOENCA);

-- TB_ARKIVE_PREDISPOSICAO: Relacionamento N:N entre racas e doencas com predisposicao genetica.
-- TB_ARKIVE_PREDISPOSICAO.ID_PREDISPOSICAO: Identificador unico do registro de predisposicao.
-- TB_ARKIVE_PREDISPOSICAO.ID_ESPECIE: Especie associada a predisposicao.
-- TB_ARKIVE_PREDISPOSICAO.ID_RACA: Raca com predisposicao.
-- TB_ARKIVE_PREDISPOSICAO.ID_DOENCA: Doenca associada a predisposicao.

CREATE TABLE TB_ARKIVE_CONSULTA (
    ID_CONSULTA BIGINT IDENTITY(1,1) NOT NULL,
    DT_HORA DATETIME2 NOT NULL,
    TP_MODALIDADE VARCHAR(20) NOT NULL,
    DS_MOTIVO VARCHAR(MAX) NOT NULL,
    DS_SINTOMAS VARCHAR(MAX) NULL,
    DS_OBSERVACAO VARCHAR(MAX) NULL,
    KG_PESO DECIMAL(6,2) NULL,
    DS_TRANSCRICAO VARCHAR(MAX) NULL,
    ST_STATUS CHAR(2) NOT NULL DEFAULT 'AG',
    ID_ANIMAL BIGINT NOT NULL,
    ID_VETERINARIO BIGINT NOT NULL,
    ID_CLINICA BIGINT NULL,

    CONSTRAINT PK_ARKIVE_CONSULTA PRIMARY KEY (ID_CONSULTA),
    CONSTRAINT CK_ARKIVE_CONS_MODALIDADE CHECK (TP_MODALIDADE IN ('PRESENCIAL', 'REMOTA')),
    CONSTRAINT CK_ARKIVE_CONS_STATUS CHECK (ST_STATUS IN ('AG', 'EP', 'AP', 'FI', 'CA')),
    CONSTRAINT CK_ARKIVE_CONS_PESO CHECK (KG_PESO IS NULL OR KG_PESO > 0),
    CONSTRAINT FK_CONS_ANIMAL FOREIGN KEY (ID_ANIMAL)
        REFERENCES TB_ARKIVE_ANIMAL (ID_ANIMAL),
    CONSTRAINT FK_CONS_VET FOREIGN KEY (ID_VETERINARIO)
        REFERENCES TB_ARKIVE_VETERINARIO (ID_VETERINARIO),
    CONSTRAINT FK_CONS_CLINICA FOREIGN KEY (ID_CLINICA)
        REFERENCES TB_ARKIVE_CLINICA (ID_CLINICA)
);
-- TB_ARKIVE_CONSULTA: Registro de atendimento veterinario presencial ou remoto.
-- TB_ARKIVE_CONSULTA.ID_CONSULTA: Identificador unico da consulta.
-- TB_ARKIVE_CONSULTA.DT_HORA: Data e hora da consulta.
-- TB_ARKIVE_CONSULTA.TP_MODALIDADE: Modalidade da consulta: Presencial ou Remota.
-- TB_ARKIVE_CONSULTA.DS_MOTIVO: Motivo principal da consulta.
-- TB_ARKIVE_CONSULTA.DS_SINTOMAS: Sintomas relatados pelo responsavel ou observados pelo veterinario.
-- TB_ARKIVE_CONSULTA.DS_OBSERVACAO: Observacoes clinicas gerais.
-- TB_ARKIVE_CONSULTA.KG_PESO: Peso registrado durante a consulta.
-- TB_ARKIVE_CONSULTA.DS_TRANSCRICAO: Texto bruto de transcricao da consulta, planejado para IA.
-- TB_ARKIVE_CONSULTA.ST_STATUS: Status da consulta: AG, EP, AP, FI ou CA.
-- TB_ARKIVE_CONSULTA.ID_ANIMAL: Animal atendido.
-- TB_ARKIVE_CONSULTA.ID_VETERINARIO: Veterinario responsavel pela consulta.
-- TB_ARKIVE_CONSULTA.ID_CLINICA: Clinica da consulta; nulo para atendimento autonomo.

CREATE TABLE TB_ARKIVE_DIAGNOSTICO (
    ID_DIAGNOSTICO BIGINT IDENTITY(1,1) NOT NULL,
    DS_DIAGNOSTICO VARCHAR(MAX) NOT NULL,
    TP_SEVERIDADE VARCHAR(20) NULL,
    ST_CONFIRMADO CHAR(1) NOT NULL DEFAULT 'S',
    DS_INSIGHT_IA VARCHAR(MAX) NULL,
    PC_CONFIANCA DECIMAL(5,2) NULL,
    ST_VALIDACAO_VET CHAR(1) NULL,
    ID_CONSULTA BIGINT NOT NULL,
    ID_DOENCA BIGINT NULL,

    CONSTRAINT PK_ARKIVE_DIAGNOSTICO PRIMARY KEY (ID_DIAGNOSTICO),
    CONSTRAINT CK_ARKIVE_DIAG_SEVERIDADE CHECK (TP_SEVERIDADE IS NULL OR TP_SEVERIDADE IN ('LEVE', 'MODERADA', 'GRAVE')),
    CONSTRAINT CK_ARKIVE_DIAG_CONFIRMADO CHECK (ST_CONFIRMADO IN ('S', 'N')),
    CONSTRAINT CK_ARKIVE_DIAG_VALIDACAO CHECK (ST_VALIDACAO_VET IS NULL OR ST_VALIDACAO_VET IN ('S', 'N')),
    CONSTRAINT CK_ARKIVE_DIAG_CONFIANCA CHECK (PC_CONFIANCA IS NULL OR PC_CONFIANCA BETWEEN 0 AND 100),
    CONSTRAINT FK_DIAG_CONSULTA FOREIGN KEY (ID_CONSULTA)
        REFERENCES TB_ARKIVE_CONSULTA (ID_CONSULTA),
    CONSTRAINT FK_DIAG_DOENCA FOREIGN KEY (ID_DOENCA)
        REFERENCES TB_ARKIVE_DOENCA (ID_DOENCA)
);
-- TB_ARKIVE_DIAGNOSTICO: Diagnostico gerado em consulta, com possibilidade de insight por IA.
-- TB_ARKIVE_DIAGNOSTICO.ID_DIAGNOSTICO: Identificador unico do diagnostico.
-- TB_ARKIVE_DIAGNOSTICO.DS_DIAGNOSTICO: Descricao do diagnostico.
-- TB_ARKIVE_DIAGNOSTICO.TP_SEVERIDADE: Severidade do diagnostico.
-- TB_ARKIVE_DIAGNOSTICO.ST_CONFIRMADO: Indica se o diagnostico esta confirmado: S ou N.
-- TB_ARKIVE_DIAGNOSTICO.DS_INSIGHT_IA: Sugestao diagnostica gerada pelo motor de regras ou IA.
-- TB_ARKIVE_DIAGNOSTICO.PC_CONFIANCA: Score de confianca do insight, entre 0 e 100.
-- TB_ARKIVE_DIAGNOSTICO.ST_VALIDACAO_VET: Aceite do veterinario sobre o insight: S ou N.
-- TB_ARKIVE_DIAGNOSTICO.ID_CONSULTA: Consulta associada ao diagnostico.
-- TB_ARKIVE_DIAGNOSTICO.ID_DOENCA: Doenca catalogada associada ao diagnostico.

CREATE TABLE TB_ARKIVE_PRESCRICAO (
    ID_PRESCRICAO BIGINT IDENTITY(1,1) NOT NULL,
    NM_MEDICAMENTO VARCHAR(150) NOT NULL,
    DS_DOSAGEM VARCHAR(50) NOT NULL,
    DS_FREQUENCIA VARCHAR(100) NULL,
    TP_VIA_ADMINISTRACAO VARCHAR(50) NULL,
    DT_INICIO DATE NOT NULL,
    DT_FIM DATE NULL,
    DS_INSTRUCOES VARCHAR(MAX) NULL,
    ID_CONSULTA BIGINT NOT NULL,

    CONSTRAINT PK_ARKIVE_PRESCRICAO PRIMARY KEY (ID_PRESCRICAO),
    CONSTRAINT CK_ARKIVE_PRESC_VIA CHECK (TP_VIA_ADMINISTRACAO IS NULL OR TP_VIA_ADMINISTRACAO IN ('ORAL', 'INJETAVEL', 'TOPICO', 'OCULAR', 'OTOLOGICO', 'OUTRO')),
    CONSTRAINT CK_ARKIVE_PRESC_DATAS CHECK (DT_FIM IS NULL OR DT_FIM >= DT_INICIO),
    CONSTRAINT FK_PRESC_CONSULTA FOREIGN KEY (ID_CONSULTA)
        REFERENCES TB_ARKIVE_CONSULTA (ID_CONSULTA)
);
-- TB_ARKIVE_PRESCRICAO: Medicamentos e tratamentos prescritos em consulta.
-- TB_ARKIVE_PRESCRICAO.ID_PRESCRICAO: Identificador unico da prescricao.
-- TB_ARKIVE_PRESCRICAO.NM_MEDICAMENTO: Nome do medicamento ou tratamento.
-- TB_ARKIVE_PRESCRICAO.DS_DOSAGEM: Dosagem prescrita.
-- TB_ARKIVE_PRESCRICAO.DS_FREQUENCIA: Frequencia de administracao.
-- TB_ARKIVE_PRESCRICAO.TP_VIA_ADMINISTRACAO: Via de administracao.
-- TB_ARKIVE_PRESCRICAO.DT_INICIO: Data inicial da prescricao.
-- TB_ARKIVE_PRESCRICAO.DT_FIM: Data final prevista da prescricao.
-- TB_ARKIVE_PRESCRICAO.DS_INSTRUCOES: Instrucoes adicionais.
-- TB_ARKIVE_PRESCRICAO.ID_CONSULTA: Consulta associada a prescricao.

CREATE TABLE TB_ARKIVE_AVALIACAO_BEM_ESTAR (
    ID_AVALIACAO_BEM_ESTAR BIGINT IDENTITY(1,1) NOT NULL,
    ID_ANIMAL BIGINT NOT NULL,
    ID_RESPONSAVEL BIGINT NULL,
    ID_VETERINARIO BIGINT NULL,
    ID_CONSULTA BIGINT NULL,
    DT_AVALIACAO DATETIME2 NOT NULL DEFAULT GETDATE(),
    NR_IDADE DECIMAL(5,2) NULL,
    KG_PESO DECIMAL(6,2) NULL,
    DS_APETITE VARCHAR(20) NULL,
    DS_ATIVIDADE VARCHAR(20) NULL,
    DS_COMPORTAMENTO VARCHAR(30) NULL,
    DS_OBSERVACAO VARCHAR(MAX) NULL,

    CONSTRAINT PK_ARKIVE_AVAL_BEM_ESTAR PRIMARY KEY (ID_AVALIACAO_BEM_ESTAR),
    CONSTRAINT CK_ARKIVE_AVAL_PESO CHECK (KG_PESO IS NULL OR KG_PESO > 0),
    CONSTRAINT CK_ARKIVE_AVAL_IDADE CHECK (NR_IDADE IS NULL OR NR_IDADE > 0),
    CONSTRAINT CK_ARKIVE_AVAL_APETITE CHECK (DS_APETITE IS NULL OR DS_APETITE IN ('SEM APETITE', 'REDUZIDO', 'NORMAL', 'AUMENTADO')),
    CONSTRAINT CK_ARKIVE_AVAL_ATIVIDADE CHECK (DS_ATIVIDADE IS NULL OR DS_ATIVIDADE IN ('BAIXA', 'NORMAL', 'ALTA')),
    CONSTRAINT CK_ARKIVE_AVAL_COMPORT CHECK (DS_COMPORTAMENTO IS NULL OR DS_COMPORTAMENTO IN ('APATICO', 'NORMAL', 'ALTERADO', 'ANSIOSO', 'AGRESSIVO')),
    CONSTRAINT CK_ARKIVE_AVAL_AUTOR CHECK (ID_RESPONSAVEL IS NOT NULL OR ID_VETERINARIO IS NOT NULL OR ID_CONSULTA IS NOT NULL),
    CONSTRAINT FK_AVAL_ANIMAL FOREIGN KEY (ID_ANIMAL)
        REFERENCES TB_ARKIVE_ANIMAL (ID_ANIMAL),
    CONSTRAINT FK_AVAL_RESP FOREIGN KEY (ID_RESPONSAVEL)
        REFERENCES TB_ARKIVE_RESPONSAVEL (ID_RESPONSAVEL),
    CONSTRAINT FK_AVAL_VET FOREIGN KEY (ID_VETERINARIO)
        REFERENCES TB_ARKIVE_VETERINARIO (ID_VETERINARIO),
    CONSTRAINT FK_AVAL_CONSULTA FOREIGN KEY (ID_CONSULTA)
        REFERENCES TB_ARKIVE_CONSULTA (ID_CONSULTA)
);
-- TB_ARKIVE_AVALIACAO_BEM_ESTAR: Avaliacoes recorrentes de bem-estar do animal, cobrindo peso, apetite, atividade, comportamento e observacoes longitudinais.
-- TB_ARKIVE_AVALIACAO_BEM_ESTAR.ID_AVALIACAO_BEM_ESTAR: Identificador unico da avaliacao de bem-estar.
-- TB_ARKIVE_AVALIACAO_BEM_ESTAR.ID_ANIMAL: Animal avaliado.
-- TB_ARKIVE_AVALIACAO_BEM_ESTAR.ID_RESPONSAVEL: Responsavel que informou a avaliacao, quando aplicavel.
-- TB_ARKIVE_AVALIACAO_BEM_ESTAR.ID_VETERINARIO: Veterinario que registrou a avaliacao, quando aplicavel.
-- TB_ARKIVE_AVALIACAO_BEM_ESTAR.ID_CONSULTA: Consulta associada a avaliacao, quando aplicavel.
-- TB_ARKIVE_AVALIACAO_BEM_ESTAR.DT_AVALIACAO: Data e hora da avaliacao.
-- TB_ARKIVE_AVALIACAO_BEM_ESTAR.KG_PESO: Peso observado do animal em quilogramas.
-- TB_ARKIVE_AVALIACAO_BEM_ESTAR.NR_IDADE: Idade real ou aproximada do animal em anos.
-- TB_ARKIVE_AVALIACAO_BEM_ESTAR.DS_APETITE: Estado de apetite observado.
-- TB_ARKIVE_AVALIACAO_BEM_ESTAR.DS_ATIVIDADE: Nivel de atividade observado.
-- TB_ARKIVE_AVALIACAO_BEM_ESTAR.DS_COMPORTAMENTO: Estado comportamental observado.
-- TB_ARKIVE_AVALIACAO_BEM_ESTAR.DS_OBSERVACAO: Observacao livre sobre rotina, nutricao, comportamento ou saude geral.

CREATE TABLE TB_ARKIVE_PROTOCOLO_PREVENTIVO (
    ID_PROTOCOLO BIGINT IDENTITY(1,1) NOT NULL,
    NM_PROTOCOLO VARCHAR(50) NOT NULL,
    TP_PROTOCOLO VARCHAR(50) NOT NULL,
    DS_PROTOCOLO VARCHAR(MAX) NULL,
    NR_INTERVALO INT NOT NULL,
    NR_IDADE_MIN INT NOT NULL DEFAULT 0,
    ID_ESPECIE BIGINT NULL,
    ID_RACA BIGINT NULL,
    ST_ATIVO CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT PK_ARKIVE_PROTOCOLO_PREV PRIMARY KEY (ID_PROTOCOLO),
    CONSTRAINT CK_ARKIVE_PROT_TIPO CHECK (TP_PROTOCOLO IN ('VACINA', 'VERMIFUGO', 'CHECK-UP', 'ANTIPARASITARIO')),
    CONSTRAINT CK_ARKIVE_PROT_INTERVALO CHECK (NR_INTERVALO > 0),
    CONSTRAINT CK_ARKIVE_PROT_IDADE CHECK (NR_IDADE_MIN >= 0),
    CONSTRAINT CK_ARKIVE_PROT_ATIVO CHECK (ST_ATIVO IN ('S', 'N')),
    CONSTRAINT FK_PROT_ESPECIE FOREIGN KEY (ID_ESPECIE)
        REFERENCES TB_ARKIVE_ESPECIE (ID_ESPECIE),
    CONSTRAINT FK_PROT_RACA FOREIGN KEY (ID_RACA)
        REFERENCES TB_ARKIVE_RACA (ID_RACA)
);
-- TB_ARKIVE_PROTOCOLO_PREVENTIVO: Template de protocolos preventivos por especie ou raca.
-- TB_ARKIVE_PROTOCOLO_PREVENTIVO.ID_PROTOCOLO: Identificador unico do protocolo preventivo.
-- TB_ARKIVE_PROTOCOLO_PREVENTIVO.NM_PROTOCOLO: Nome do protocolo, como Vacina V10.
-- TB_ARKIVE_PROTOCOLO_PREVENTIVO.TP_PROTOCOLO: Tipo do protocolo preventivo.
-- TB_ARKIVE_PROTOCOLO_PREVENTIVO.DS_PROTOCOLO: Descricao do protocolo.
-- TB_ARKIVE_PROTOCOLO_PREVENTIVO.NR_INTERVALO: Intervalo recomendado em dias.
-- TB_ARKIVE_PROTOCOLO_PREVENTIVO.NR_IDADE_MIN: Idade minima recomendada em meses.
-- TB_ARKIVE_PROTOCOLO_PREVENTIVO.ID_ESPECIE: Especie alvo do protocolo; nulo quando geral ou especifico por raca.
-- TB_ARKIVE_PROTOCOLO_PREVENTIVO.ID_RACA: Raca alvo do protocolo; nulo quando geral ou por especie.
-- TB_ARKIVE_PROTOCOLO_PREVENTIVO.ST_ATIVO: Indica exclusao logica: S = ativo, N = inativo.

CREATE TABLE TB_ARKIVE_EVENTO_PREVENTIVO (
    ID_EVENTO_PREV BIGINT IDENTITY(1,1) NOT NULL,
    DT_APLICACAO DATE NULL,
    DT_PROXIMO DATE NOT NULL,
    ST_STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    ST_ALERTA CHAR(1) NOT NULL DEFAULT 'N',
    DS_OBSERVACAO VARCHAR(MAX) NULL,
    ID_ANIMAL BIGINT NOT NULL,
    ID_PROTOCOLO BIGINT NOT NULL,
    ID_CONSULTA BIGINT NULL,

    CONSTRAINT PK_ARKIVE_EVENTO_PREV PRIMARY KEY (ID_EVENTO_PREV),
    CONSTRAINT CK_ARKIVE_EVTPREV_STATUS CHECK (ST_STATUS IN ('REALIZADO', 'PENDENTE', 'ATRASADO')),
    CONSTRAINT CK_ARKIVE_EVTPREV_ALERTA CHECK (ST_ALERTA IN ('S', 'N')),
    CONSTRAINT CK_ARKIVE_EVTPREV_APLIC CHECK (
        (ST_STATUS = 'REALIZADO' AND DT_APLICACAO IS NOT NULL)
        OR
        (ST_STATUS IN ('PENDENTE', 'ATRASADO') AND DT_APLICACAO IS NULL)
    ),
    CONSTRAINT CK_ARKIVE_EVTPREV_DATAS CHECK (DT_APLICACAO IS NULL OR DT_PROXIMO >= DT_APLICACAO),
    CONSTRAINT FK_EVTPREV_ANIMAL FOREIGN KEY (ID_ANIMAL)
        REFERENCES TB_ARKIVE_ANIMAL (ID_ANIMAL),
    CONSTRAINT FK_EVTPREV_PROTOCOLO FOREIGN KEY (ID_PROTOCOLO)
        REFERENCES TB_ARKIVE_PROTOCOLO_PREVENTIVO (ID_PROTOCOLO),
    CONSTRAINT FK_EVTPREV_CONSULTA FOREIGN KEY (ID_CONSULTA)
        REFERENCES TB_ARKIVE_CONSULTA (ID_CONSULTA)
);
-- TB_ARKIVE_EVENTO_PREVENTIVO: Instancia de aplicacao ou vencimento de um protocolo preventivo para um animal.
-- TB_ARKIVE_EVENTO_PREVENTIVO.ID_EVENTO_PREV: Identificador unico do evento preventivo.
-- TB_ARKIVE_EVENTO_PREVENTIVO.DT_APLICACAO: Data de aplicacao, obrigatoria apenas quando realizado.
-- TB_ARKIVE_EVENTO_PREVENTIVO.DT_PROXIMO: Proxima data prevista para o cuidado preventivo.
-- TB_ARKIVE_EVENTO_PREVENTIVO.ST_STATUS: Status do evento preventivo.
-- TB_ARKIVE_EVENTO_PREVENTIVO.ST_ALERTA: Indica se alerta ja foi disparado: S ou N.
-- TB_ARKIVE_EVENTO_PREVENTIVO.DS_OBSERVACAO: Observacoes sobre o evento preventivo.
-- TB_ARKIVE_EVENTO_PREVENTIVO.ID_ANIMAL: Animal relacionado ao evento.
-- TB_ARKIVE_EVENTO_PREVENTIVO.ID_PROTOCOLO: Protocolo preventivo aplicado.
-- TB_ARKIVE_EVENTO_PREVENTIVO.ID_CONSULTA: Consulta que originou o evento, quando aplicavel.

CREATE TABLE TB_ARKIVE_ALERTA (
    ID_ALERTA BIGINT IDENTITY(1,1) NOT NULL,
    TP_ALERTA VARCHAR(50) NOT NULL,
    DS_MENSAGEM VARCHAR(MAX) NOT NULL,
    DT_ENVIO DATETIME2 NOT NULL DEFAULT GETDATE(),
    DT_LEITURA DATETIME2 NULL,
    ST_STATUS VARCHAR(20) NOT NULL DEFAULT 'ENVIADO',
    TP_CANAL VARCHAR(20) NOT NULL,
    ID_ANIMAL BIGINT NOT NULL,
    ID_RESPONSAVEL BIGINT NULL,
    ID_CLINICA BIGINT NULL,
    ID_EVENTO_PREV BIGINT NULL,

    CONSTRAINT PK_ARKIVE_ALERTA PRIMARY KEY (ID_ALERTA),
    CONSTRAINT CK_ARKIVE_ALERTA_TIPO CHECK (TP_ALERTA IN ('VACINA', 'RETORNO', 'MEDICAMENTO', 'CHECK-UP')),
    CONSTRAINT CK_ARKIVE_ALERTA_STATUS CHECK (ST_STATUS IN ('ENVIADO', 'LIDO', 'IGNORADO')),
    CONSTRAINT CK_ARKIVE_ALERTA_CANAL CHECK (TP_CANAL IN ('APP', 'WHATSAPP', 'EMAIL')),
    CONSTRAINT CK_ARKIVE_ALERTA_LEITURA CHECK (DT_LEITURA IS NULL OR DT_LEITURA >= DT_ENVIO),
    CONSTRAINT CK_ARKIVE_ALERTA_DESTINO CHECK (ID_RESPONSAVEL IS NOT NULL OR ID_CLINICA IS NOT NULL),
    CONSTRAINT FK_ALERTA_ANIMAL FOREIGN KEY (ID_ANIMAL)
        REFERENCES TB_ARKIVE_ANIMAL (ID_ANIMAL),
    CONSTRAINT FK_ALERTA_RESP FOREIGN KEY (ID_RESPONSAVEL)
        REFERENCES TB_ARKIVE_RESPONSAVEL (ID_RESPONSAVEL),
    CONSTRAINT FK_ALERTA_CLINICA FOREIGN KEY (ID_CLINICA)
        REFERENCES TB_ARKIVE_CLINICA (ID_CLINICA),
    CONSTRAINT FK_ALERTA_EVTPREV FOREIGN KEY (ID_EVENTO_PREV)
        REFERENCES TB_ARKIVE_EVENTO_PREVENTIVO (ID_EVENTO_PREV)
);
-- TB_ARKIVE_ALERTA: Notificacoes enviadas para responsaveis, clinicas ou equipe operacional.
-- TB_ARKIVE_ALERTA.ID_ALERTA: Identificador unico do alerta.
-- TB_ARKIVE_ALERTA.TP_ALERTA: Tipo do alerta.
-- TB_ARKIVE_ALERTA.DS_MENSAGEM: Mensagem enviada.
-- TB_ARKIVE_ALERTA.DT_ENVIO: Data e hora de envio do alerta.
-- TB_ARKIVE_ALERTA.DT_LEITURA: Data e hora de leitura do alerta.
-- TB_ARKIVE_ALERTA.ST_STATUS: Status do alerta.
-- TB_ARKIVE_ALERTA.TP_CANAL: Canal utilizado para envio.
-- TB_ARKIVE_ALERTA.ID_ANIMAL: Animal associado ao alerta.
-- TB_ARKIVE_ALERTA.ID_RESPONSAVEL: Responsavel destinatario do alerta, quando aplicavel.
-- TB_ARKIVE_ALERTA.ID_CLINICA: Clinica destinataria do alerta, quando aplicavel.
-- TB_ARKIVE_ALERTA.ID_EVENTO_PREV: Evento preventivo que originou o alerta, quando aplicavel.

CREATE TABLE TB_ARKIVE_EVENTO_JORNADA (
    ID_EVENTO_JORN BIGINT IDENTITY(1,1) NOT NULL,
    TP_EVENTO VARCHAR(50) NOT NULL,
    DT_EVENTO DATETIME2 NOT NULL DEFAULT GETDATE(),
    TP_ORIGEM VARCHAR(30) NOT NULL,
    TP_ATOR VARCHAR(30) NULL,
    ID_RESPONSAVEL BIGINT NULL,
    ID_VETERINARIO BIGINT NULL,
    ID_ANIMAL BIGINT NULL,
    ID_CLINICA BIGINT NULL,
    DS_CANAL VARCHAR(30) NULL,
    DS_CONTEXTO VARCHAR(MAX) NULL,
    PAYLOAD_JSON VARCHAR(MAX) NULL,

    CONSTRAINT PK_ARKIVE_EVENTO_JORNADA PRIMARY KEY (ID_EVENTO_JORN),
    CONSTRAINT CK_ARKIVE_EVTJ_ORIGEM CHECK (TP_ORIGEM IN ('APP', 'WEB', 'WHATSAPP', 'API', 'IA', 'SISTEMA')),
    CONSTRAINT CK_ARKIVE_EVTJ_ATOR CHECK (TP_ATOR IS NULL OR TP_ATOR IN ('RESPONSAVEL', 'VETERINARIO', 'CLINICA', 'SISTEMA', 'IA')),
    CONSTRAINT FK_EVTJ_RESP FOREIGN KEY (ID_RESPONSAVEL)
        REFERENCES TB_ARKIVE_RESPONSAVEL (ID_RESPONSAVEL),
    CONSTRAINT FK_EVTJ_VET FOREIGN KEY (ID_VETERINARIO)
        REFERENCES TB_ARKIVE_VETERINARIO (ID_VETERINARIO),
    CONSTRAINT FK_EVTJ_ANIMAL FOREIGN KEY (ID_ANIMAL)
        REFERENCES TB_ARKIVE_ANIMAL (ID_ANIMAL),
    CONSTRAINT FK_EVTJ_CLINICA FOREIGN KEY (ID_CLINICA)
        REFERENCES TB_ARKIVE_CLINICA (ID_CLINICA),
    CONSTRAINT CK_ARKIVE_EVTJ_PAYLOAD_JSON CHECK (PAYLOAD_JSON IS NULL OR ISJSON(PAYLOAD_JSON) = 1)
);
-- TB_ARKIVE_EVENTO_JORNADA: Tabela append-only de eventos relevantes da jornada do responsavel, pet, veterinario e clinica. Serve como ponte para analytics, datahouse e futura camada de dados.
-- TB_ARKIVE_EVENTO_JORNADA.ID_EVENTO_JORN: Identificador unico do evento de jornada.
-- TB_ARKIVE_EVENTO_JORNADA.TP_EVENTO: Tipo do evento de negocio. Ex: ANIMAL_CADASTRADO, ALERTA_LIDO, CONSULTA_CRIADA.
-- TB_ARKIVE_EVENTO_JORNADA.DT_EVENTO: Data e hora em que o evento ocorreu.
-- TB_ARKIVE_EVENTO_JORNADA.TP_ORIGEM: Origem tecnica do evento: APP, WEB, WHATSAPP, API, IA ou SISTEMA.
-- TB_ARKIVE_EVENTO_JORNADA.TP_ATOR: Ator responsavel pelo evento: RESPONSAVEL, VETERINARIO, CLINICA, SISTEMA ou IA.
-- TB_ARKIVE_EVENTO_JORNADA.ID_RESPONSAVEL: Responsavel relacionado ao evento, quando aplicavel.
-- TB_ARKIVE_EVENTO_JORNADA.ID_VETERINARIO: Veterinario relacionado ao evento, quando aplicavel.
-- TB_ARKIVE_EVENTO_JORNADA.ID_ANIMAL: Animal relacionado ao evento, quando aplicavel.
-- TB_ARKIVE_EVENTO_JORNADA.ID_CLINICA: Clinica relacionada ao evento, quando aplicavel.
-- TB_ARKIVE_EVENTO_JORNADA.DS_CANAL: Canal funcional do evento, como MOBILE, WEB, WHATSAPP ou JOB.
-- TB_ARKIVE_EVENTO_JORNADA.DS_CONTEXTO: Descricao curta do contexto de negocio do evento.
-- TB_ARKIVE_EVENTO_JORNADA.PAYLOAD_JSON: Dados complementares em JSON textual para alimentar analises futuras.

CREATE TABLE TB_ARKIVE_ADESAO_PRESCRICAO (
    ID_ADESAO BIGINT IDENTITY(1,1) NOT NULL,
    ID_PRESCRICAO BIGINT NOT NULL,
    ID_RESPONSAVEL BIGINT NULL,
    ID_ANIMAL BIGINT NOT NULL,
    DT_REGISTRO DATETIME2 NOT NULL DEFAULT GETDATE(),
    ST_TOMOU CHAR(1) NOT NULL,
    DS_OBSERVACAO VARCHAR(MAX) NULL,

    CONSTRAINT PK_ARKIVE_ADESAO_PRESCRICAO PRIMARY KEY (ID_ADESAO),
    CONSTRAINT CK_ARKIVE_ADESAO_TOMOU CHECK (ST_TOMOU IN ('S', 'N')),
    CONSTRAINT FK_ADESAO_PRESCRICAO FOREIGN KEY (ID_PRESCRICAO)
        REFERENCES TB_ARKIVE_PRESCRICAO (ID_PRESCRICAO),
    CONSTRAINT FK_ADESAO_RESP FOREIGN KEY (ID_RESPONSAVEL)
        REFERENCES TB_ARKIVE_RESPONSAVEL (ID_RESPONSAVEL),
    CONSTRAINT FK_ADESAO_ANIMAL FOREIGN KEY (ID_ANIMAL)
        REFERENCES TB_ARKIVE_ANIMAL (ID_ANIMAL)
);
-- TB_ARKIVE_ADESAO_PRESCRICAO: Registra se uma prescricao foi seguida ou nao, sustentando analises de adesao terapeutica e abandono de tratamento.
-- TB_ARKIVE_ADESAO_PRESCRICAO.ID_ADESAO: Identificador unico do registro de adesao.
-- TB_ARKIVE_ADESAO_PRESCRICAO.ID_PRESCRICAO: Prescricao relacionada ao registro de adesao.
-- TB_ARKIVE_ADESAO_PRESCRICAO.ID_RESPONSAVEL: Responsavel que informou a adesao, quando aplicavel.
-- TB_ARKIVE_ADESAO_PRESCRICAO.ID_ANIMAL: Animal relacionado a prescricao.
-- TB_ARKIVE_ADESAO_PRESCRICAO.DT_REGISTRO: Data e hora do registro de adesao.
-- TB_ARKIVE_ADESAO_PRESCRICAO.ST_TOMOU: Indica se a dose/tratamento foi seguido: S ou N.
-- TB_ARKIVE_ADESAO_PRESCRICAO.DS_OBSERVACAO: Observacao opcional do responsavel, clinica ou sistema.

CREATE TABLE TB_ARKIVE_FEEDBACK_NPS (
    ID_FEEDBACK_NPS BIGINT IDENTITY(1,1) NOT NULL,
    ID_VETERINARIO BIGINT NULL,
    ID_RESPONSAVEL BIGINT NULL,
    ID_ANIMAL BIGINT NULL,
    ID_CLINICA BIGINT NULL,
    ID_CONSULTA BIGINT NULL,
    NR_NOTA INT NOT NULL,
    DS_COMENTARIO VARCHAR(MAX) NULL,
    DT_FEEDBACK DATETIME2 NOT NULL DEFAULT GETDATE(),

    CONSTRAINT PK_ARKIVE_FEEDBACK_NPS PRIMARY KEY (ID_FEEDBACK_NPS),
    CONSTRAINT CK_ARKIVE_NPS_NOTA CHECK (NR_NOTA BETWEEN 0 AND 5),
    CONSTRAINT CK_ARKIVE_NPS_CONTEXTO CHECK (ID_VETERINARIO IS NOT NULL OR ID_RESPONSAVEL IS NOT NULL OR ID_ANIMAL IS NOT NULL OR ID_CLINICA IS NOT NULL OR ID_CONSULTA IS NOT NULL),
    CONSTRAINT FK_NPS_VET FOREIGN KEY (ID_VETERINARIO)
        REFERENCES TB_ARKIVE_VETERINARIO (ID_VETERINARIO),
    CONSTRAINT FK_NPS_RESP FOREIGN KEY (ID_RESPONSAVEL)
        REFERENCES TB_ARKIVE_RESPONSAVEL (ID_RESPONSAVEL),
    CONSTRAINT FK_NPS_ANIMAL FOREIGN KEY (ID_ANIMAL)
        REFERENCES TB_ARKIVE_ANIMAL (ID_ANIMAL),
    CONSTRAINT FK_NPS_CLINICA FOREIGN KEY (ID_CLINICA)
        REFERENCES TB_ARKIVE_CLINICA (ID_CLINICA),
    CONSTRAINT FK_NPS_CONSULTA FOREIGN KEY (ID_CONSULTA)
        REFERENCES TB_ARKIVE_CONSULTA (ID_CONSULTA)
);
-- TB_ARKIVE_FEEDBACK_NPS: Feedback de satisfacao em escala de 0 a 5 estrelas, relacionado ao app, clinica, consulta, animal ou responsavel.
-- TB_ARKIVE_FEEDBACK_NPS.ID_FEEDBACK_NPS: Identificador unico do feedback NPS.
-- TB_ARKIVE_FEEDBACK_NPS.ID_VETERINARIO: Veterinario associado ao feedback, quando aplicavel.
-- TB_ARKIVE_FEEDBACK_NPS.ID_RESPONSAVEL: Responsavel que enviou o feedback, quando aplicavel.
-- TB_ARKIVE_FEEDBACK_NPS.ID_ANIMAL: Animal associado ao feedback, quando aplicavel.
-- TB_ARKIVE_FEEDBACK_NPS.ID_CLINICA: Clinica associada ao feedback, quando aplicavel.
-- TB_ARKIVE_FEEDBACK_NPS.ID_CONSULTA: Consulta associada ao feedback, quando aplicavel.
-- TB_ARKIVE_FEEDBACK_NPS.NR_NOTA: Nota de feedback em escala de 0 a 5 estrelas.
-- TB_ARKIVE_FEEDBACK_NPS.DS_COMENTARIO: Comentario livre opcional.
-- TB_ARKIVE_FEEDBACK_NPS.DT_FEEDBACK: Data e hora de envio do feedback.

CREATE TABLE TB_ARKIVE_LOG_ERRO (
    ID_LOG_ERRO BIGINT IDENTITY(1,1) NOT NULL,
    NM_PROCEDURE VARCHAR(100) NOT NULL,
    NM_USUARIO VARCHAR(100) NOT NULL DEFAULT USER_NAME(),
    DT_OCORRENCIA DATETIME2 NOT NULL DEFAULT GETDATE(),
    CD_ERRO INT NOT NULL,
    DS_MENSAGEM_ERRO VARCHAR(MAX) NOT NULL,

    CONSTRAINT PK_ARKIVE_LOG_ERRO PRIMARY KEY (ID_LOG_ERRO)
);
-- TB_ARKIVE_LOG_ERRO: Auditoria de erros gerados por procedures e rotinas de banco de dados.
-- TB_ARKIVE_LOG_ERRO.ID_LOG_ERRO: Identificador unico do log de erro.
-- TB_ARKIVE_LOG_ERRO.NM_PROCEDURE: Nome da procedure ou rotina que gerou o erro.
-- TB_ARKIVE_LOG_ERRO.NM_USUARIO: Usuario do banco de dados que executou a rotina.
-- TB_ARKIVE_LOG_ERRO.DT_OCORRENCIA: Data e hora da ocorrencia do erro.
-- TB_ARKIVE_LOG_ERRO.CD_ERRO: Codigo do erro.
-- TB_ARKIVE_LOG_ERRO.DS_MENSAGEM_ERRO: Mensagem descritiva do erro.

/*
  --------------------------------------------------------------------------------
==================================================================================
   # 2 - CRIACAO DE INDICES NAO-IMPLICITOS
  --------------------------------------------------------------------------------
*/

CREATE INDEX IX_ARKIVE_RACA_ESPECIE ON TB_ARKIVE_RACA (ID_ESPECIE);
CREATE INDEX IX_ARKIVE_RESPCLDS_CLINICA ON TB_ARKIVE_RESPONSAVEL_CLINICA (ID_CLINICA);
CREATE INDEX IX_ARKIVE_VET_CLINICA ON TB_ARKIVE_VETERINARIO (ID_CLINICA);
CREATE INDEX IX_ARKIVE_ANIMAL_ESPECIE ON TB_ARKIVE_ANIMAL (ID_ESPECIE);
CREATE INDEX IX_ARKIVE_ANIMAL_RACA ON TB_ARKIVE_ANIMAL (ID_RACA);
CREATE INDEX IX_ARKIVE_ANIMAL_CLINICA_CAD ON TB_ARKIVE_ANIMAL (ID_CLINICA);
CREATE INDEX IX_ARKIVE_ANIRESP_RESP ON TB_ARKIVE_RESPONSAVEL_ANIMAL (ID_RESPONSAVEL);
CREATE INDEX IX_ARKIVE_DOENCA_CATEGORIA ON TB_ARKIVE_DOENCA (ID_CATEGORIA);
CREATE INDEX IX_ARKIVE_PRED_DOENCA ON TB_ARKIVE_PREDISPOSICAO (ID_DOENCA);
CREATE INDEX IX_ARKIVE_CONS_ANIMAL ON TB_ARKIVE_CONSULTA (ID_ANIMAL);
CREATE INDEX IX_ARKIVE_CONS_VET ON TB_ARKIVE_CONSULTA (ID_VETERINARIO);
CREATE INDEX IX_ARKIVE_CONS_CLINICA ON TB_ARKIVE_CONSULTA (ID_CLINICA);
CREATE INDEX IX_ARKIVE_DIAG_CONSULTA ON TB_ARKIVE_DIAGNOSTICO (ID_CONSULTA);
CREATE INDEX IX_ARKIVE_DIAG_DOENCA ON TB_ARKIVE_DIAGNOSTICO (ID_DOENCA);
CREATE INDEX IX_ARKIVE_PRESC_CONSULTA ON TB_ARKIVE_PRESCRICAO (ID_CONSULTA);
CREATE INDEX IX_ARKIVE_AVAL_ANIMAL ON TB_ARKIVE_AVALIACAO_BEM_ESTAR (ID_ANIMAL);
CREATE INDEX IX_ARKIVE_AVAL_RESP ON TB_ARKIVE_AVALIACAO_BEM_ESTAR (ID_RESPONSAVEL);
CREATE INDEX IX_ARKIVE_AVAL_VET ON TB_ARKIVE_AVALIACAO_BEM_ESTAR (ID_VETERINARIO);
CREATE INDEX IX_ARKIVE_AVAL_CONSULTA ON TB_ARKIVE_AVALIACAO_BEM_ESTAR (ID_CONSULTA);
CREATE INDEX IX_ARKIVE_PROT_ESPECIE ON TB_ARKIVE_PROTOCOLO_PREVENTIVO (ID_ESPECIE);
CREATE INDEX IX_ARKIVE_PROT_RACA ON TB_ARKIVE_PROTOCOLO_PREVENTIVO (ID_RACA);
CREATE INDEX IX_ARKIVE_EVTPREV_ANIMAL ON TB_ARKIVE_EVENTO_PREVENTIVO (ID_ANIMAL);
CREATE INDEX IX_ARKIVE_EVTPREV_PROTOCOLO ON TB_ARKIVE_EVENTO_PREVENTIVO (ID_PROTOCOLO);
CREATE INDEX IX_ARKIVE_EVTPREV_CONSULTA ON TB_ARKIVE_EVENTO_PREVENTIVO (ID_CONSULTA);
CREATE INDEX IX_ARKIVE_ALERTA_ANIMAL ON TB_ARKIVE_ALERTA (ID_ANIMAL);
CREATE INDEX IX_ARKIVE_ALERTA_RESP ON TB_ARKIVE_ALERTA (ID_RESPONSAVEL);
CREATE INDEX IX_ARKIVE_ALERTA_CLINICA ON TB_ARKIVE_ALERTA (ID_CLINICA);
CREATE INDEX IX_ARKIVE_ALERTA_EVTPREV ON TB_ARKIVE_ALERTA (ID_EVENTO_PREV);
CREATE INDEX IX_ARKIVE_EVTJ_TIPO_DATA ON TB_ARKIVE_EVENTO_JORNADA (TP_EVENTO, DT_EVENTO);
CREATE INDEX IX_ARKIVE_EVTJ_RESP ON TB_ARKIVE_EVENTO_JORNADA (ID_RESPONSAVEL);
CREATE INDEX IX_ARKIVE_EVTJ_VET ON TB_ARKIVE_EVENTO_JORNADA (ID_VETERINARIO);
CREATE INDEX IX_ARKIVE_EVTJ_ANIMAL ON TB_ARKIVE_EVENTO_JORNADA (ID_ANIMAL);
CREATE INDEX IX_ARKIVE_EVTJ_CLINICA ON TB_ARKIVE_EVENTO_JORNADA (ID_CLINICA);
CREATE INDEX IX_ARKIVE_ADESAO_PRESC ON TB_ARKIVE_ADESAO_PRESCRICAO (ID_PRESCRICAO);
CREATE INDEX IX_ARKIVE_ADESAO_RESP ON TB_ARKIVE_ADESAO_PRESCRICAO (ID_RESPONSAVEL);
CREATE INDEX IX_ARKIVE_ADESAO_ANIMAL ON TB_ARKIVE_ADESAO_PRESCRICAO (ID_ANIMAL);
CREATE INDEX IX_ARKIVE_NPS_VET ON TB_ARKIVE_FEEDBACK_NPS (ID_VETERINARIO);
CREATE INDEX IX_ARKIVE_NPS_RESP ON TB_ARKIVE_FEEDBACK_NPS (ID_RESPONSAVEL);
CREATE INDEX IX_ARKIVE_NPS_ANIMAL ON TB_ARKIVE_FEEDBACK_NPS (ID_ANIMAL);
CREATE INDEX IX_ARKIVE_NPS_CLINICA ON TB_ARKIVE_FEEDBACK_NPS (ID_CLINICA);
CREATE INDEX IX_ARKIVE_NPS_CONSULTA ON TB_ARKIVE_FEEDBACK_NPS (ID_CONSULTA);

/*
  --------------------------------------------------------------------------------
==================================================================================

FIM DO SCRIPT

  Total de objetos criados:
  --------------------------------------------------------------------------------
   23 Tabelas                       (TB_ARKIVE_*)
   31 Indices unicos implicitos     ('PK' e 'UNIQUE' constraints)
   41 Indices explicitos            (IX_ARKIVE_*)
    3 Indices unicos explicitos     (UX_ARKIVE_PREDISPOSICAO, UQ_ARKIVE_USUARIO_RESP, UQ_ARKIVE_USUARIO_VET;
                                     os dois ultimos sao filtered indexes por serem colunas
                                     opcionais 1:1, ao contrario do UNIQUE constraint do Oracle)
*/
