ALTER TABLE TB_ARKIVE_USUARIO ADD
    ST_TROCA_SENHA CHAR(1) NOT NULL DEFAULT 'N',
    DT_ULTIMA_TROCA_SENHA DATETIME2 NULL;

ALTER TABLE TB_ARKIVE_USUARIO ADD CONSTRAINT CK_ARKIVE_USUARIO_TROCA_SENHA
    CHECK (ST_TROCA_SENHA IN ('S', 'N'));

-- TB_ARKIVE_USUARIO.ST_TROCA_SENHA: Indica se o usuario deve trocar a senha no proximo acesso: S ou N.
-- TB_ARKIVE_USUARIO.DT_ULTIMA_TROCA_SENHA: Data e hora da ultima troca de senha.
