ALTER TABLE TB_ARKIVE_ANIMAL ADD
    ID_VETERINARIO_CADASTRO BIGINT NULL;
GO

ALTER TABLE TB_ARKIVE_ANIMAL ADD CONSTRAINT FK_ANIMAL_VET_CADASTRO
    FOREIGN KEY (ID_VETERINARIO_CADASTRO)
    REFERENCES TB_ARKIVE_VETERINARIO (ID_VETERINARIO);

CREATE INDEX IX_ARKIVE_ANIMAL_VET_CADASTRO
    ON TB_ARKIVE_ANIMAL (ID_VETERINARIO_CADASTRO);

-- TB_ARKIVE_ANIMAL.ID_VETERINARIO_CADASTRO: Veterinario que cadastrou o animal diretamente; nulo para cadastros administrativos ou legados.
